FROM nginx:1.13.5-alpine

ADD ./default.conf /etc/nginx/conf.d/default.conf

# Set upstream conf and remove the default conf
# RUN echo "upstream php-upstream { server 127.0.0.1:9000; }" > /etc/nginx/conf.d/upstream.conf
